### ISSUE TITLE
Is the OOM issue addressed?

### ISSUE THREAD

**Issue by SKPsanjeevi** [ROCm/hipBLASLt#1313]
I am seeing that threads are limited to 64 due to OOM issue per the comment:

https://github.com/ROCm/hipBLASLt/blob/dd8fe363e560c3f2cf19eadd10278ce51f5a181b/tensilelite/Tensile/Parallel.py#L50

Is this issue rectified? Or is it okay for users to modify the max threads limitation which is 64?

**Comment by harkgill-amd** [comment]
Hi @SKPsanjeevi, let me clarify the status of the OOM issue, and I'll get back to you shortly

**Comment by Wintoplay** [comment]
I can't build. I face OOM.
cpu vram: 33.4GB

**Comment by harkgill-amd** [comment]
Hi @SKPsanjeevi, spoke with the internal team and this workaround was put in place to ensure that internal CI builds don't error out due to OOM. Feel free to adjust the limitation to better suit your own configuration.

@Wintoplay, try reducing the number of CPU threads used during the build process by adjusting the value at https://github.com/ROCm/hipBLASLt/blob/dd8fe363e560c3f2cf19eadd10278ce51f5a181b/tensilelite/Tensile/Parallel.py#L50 This should help lower memory overhead. If you're still encountering errors after adjusting the value, please create a new issue with details on your hardware config as well as the exact error you're hitting.
